"""Step 13: model comparison, explainability, and confidence analysis.

This module uses the existing trained questionnaire models and cross-validation
outputs to select a preferred model, generate feature-level explanations,
compute a transparent project-level confidence indicator, and save artifacts
required for downstream prediction/fusion steps.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, List

import joblib
import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

PROJECT_ROOT = Path(__file__).resolve().parents[3]
DATASET_PATH = PROJECT_ROOT / "data" / "processed" / "questionnaire_with_target.csv"
MODELS_DIR = PROJECT_ROOT / "models" / "questionnaire"
RESULTS_DIR = PROJECT_ROOT / "results" / "questionnaire"

MODEL_COMPARISON_PATH = RESULTS_DIR / "model_comparison.csv"
SELECTED_MODEL_PATH = MODELS_DIR / "selected_model.json"
EXPLAINABILITY_METADATA_PATH = MODELS_DIR / "explainability_metadata.json"

TARGET_COLUMNS = {"Q4", "Q4_encoded", "stress_level", "stress_level_encoded"}
PROBABILITY_COLUMNS = ["prob_low", "prob_moderate", "prob_high"]
CLASS_ORDER = ["low", "moderate", "high"]
CONFIDENCE_THRESHOLDS = {"high": 0.70, "moderate": 0.50}


def load_json(path: Path) -> Dict[str, Any]:
    """Load JSON content from disk."""

    if not path.exists():
        raise FileNotFoundError(f"JSON file not found: {path}")

    return json.loads(path.read_text(encoding="utf-8"))


def load_model_results() -> pd.DataFrame:
    """Load the saved model comparison CSV generated by Step 12."""

    path = MODEL_COMPARISON_PATH
    if not path.exists():
        raise FileNotFoundError(f"Model comparison CSV not found: {path}")

    return pd.read_csv(path)


def load_feature_metadata() -> Dict[str, Any]:
    """Load the saved feature metadata from the model training step."""

    feature_metadata_path = MODELS_DIR / "questionnaire_feature_names.json"
    return load_json(feature_metadata_path)


def load_training_metadata() -> Dict[str, Any]:
    """Load the saved training metadata."""

    training_metadata_path = MODELS_DIR / "training_metadata.json"
    return load_json(training_metadata_path)


def validate_model_results(model_results: pd.DataFrame) -> None:
    """Validate that the Step 12 comparison table contains the expected models."""

    required_models = {"logistic_regression", "random_forest"}
    present_models = set(model_results["model"].tolist())

    missing_models = required_models - present_models
    if missing_models:
        raise ValueError(f"Model comparison table is missing required models: {', '.join(sorted(missing_models))}")


def select_model(model_results: pd.DataFrame) -> Dict[str, Any]:
    """Select the preferred model using CV evidence with a transparent ordering."""

    validate_model_results(model_results)

    logistic_row = model_results[model_results["model"] == "logistic_regression"].iloc[0]
    random_forest_row = model_results[model_results["model"] == "random_forest"].iloc[0]

    def compare_risk(row_a: pd.Series, row_b: pd.Series) -> str:
        if row_a["macro_f1_mean"] != row_b["macro_f1_mean"]:
            return row_a["model"] if row_a["macro_f1_mean"] > row_b["macro_f1_mean"] else row_b["model"]

        if row_a["balanced_accuracy_mean"] != row_b["balanced_accuracy_mean"]:
            return row_a["model"] if row_a["balanced_accuracy_mean"] > row_b["balanced_accuracy_mean"] else row_b["model"]

        if row_a["macro_f1_std"] != row_b["macro_f1_std"]:
            return row_a["model"] if row_a["macro_f1_std"] < row_b["macro_f1_std"] else row_b["model"]

        if row_a["balanced_accuracy_std"] != row_b["balanced_accuracy_std"]:
            return row_a["model"] if row_a["balanced_accuracy_std"] < row_b["balanced_accuracy_std"] else row_b["model"]

        return "logistic_regression"

    selected_model = compare_risk(random_forest_row, logistic_row)

    selected_row = model_results[model_results["model"] == selected_model].iloc[0]

    if selected_model == "random_forest":
        selection_basis = (
            f"Selected Random Forest because its cross-validation Macro F1 mean ({selected_row['macro_f1_mean']:.4f}) "
            f"and Balanced Accuracy mean ({selected_row['balanced_accuracy_mean']:.4f}) were higher than Logistic Regression."
        )
    else:
        selection_basis = (
            f"Selected Logistic Regression because the model comparison showed stronger stability and interpretability with "
            f"Macro F1 ({selected_row['macro_f1_mean']:.4f}) and Balanced Accuracy ({selected_row['balanced_accuracy_mean']:.4f}) under the CV criteria."
        )

    selected_model_record = {
        "selected_model": selected_model,
        "selection_basis": selection_basis,
        "macro_f1_mean": float(selected_row["macro_f1_mean"]),
        "balanced_accuracy_mean": float(selected_row["balanced_accuracy_mean"]),
        "cv_based": True,
    }

    SELECTED_MODEL_PATH.parent.mkdir(parents=True, exist_ok=True)
    SELECTED_MODEL_PATH.write_text(json.dumps(selected_model_record, indent=2), encoding="utf-8")

    return selected_model_record


def load_selected_model() -> Dict[str, Any]:
    """Load the selected model metadata JSON."""

    return load_json(SELECTED_MODEL_PATH)


def save_explainability_metadata(
    selected_model: str,
    top_features: List[Dict[str, Any]],
    confidence_method: str,
    confidence_thresholds: Dict[str, float],
) -> Dict[str, Any]:
    """Save machine-readable explainability metadata."""

    metadata = {
        "selected_model": selected_model,
        "top_features": top_features,
        "confidence_method": confidence_method,
        "confidence_thresholds": confidence_thresholds,
        "clinical_certainty": False,
    }

    EXPLAINABILITY_METADATA_PATH.parent.mkdir(parents=True, exist_ok=True)
    EXPLAINABILITY_METADATA_PATH.write_text(json.dumps(metadata, indent=2), encoding="utf-8")
    return metadata


def extract_random_forest_importance(
    model_path: Path,
    feature_names: List[str],
) -> pd.DataFrame:
    """Extract feature importance values from the saved random forest model."""

    model = joblib.load(model_path)
    if "model" not in model.named_steps:
        raise ValueError("Loaded Random Forest artifact does not appear to be a sklearn pipeline.")

    rf_estimator = model.named_steps["model"]
    rf_importances = np.asarray(rf_estimator.feature_importances_, dtype=float)

    if len(feature_names) != len(rf_importances):
        raise ValueError(
            f"Feature count mismatch for Random Forest: expected {len(feature_names)}, found {len(rf_importances)}."
        )

    importance_df = pd.DataFrame(
        {
            "feature": feature_names,
            "importance": rf_importances,
        }
    )

    importance_df = importance_df.sort_values("importance", ascending=False).reset_index(drop=True)
    importance_df["rank"] = np.arange(1, len(importance_df) + 1)

    RESULTS_DIR.mkdir(parents=True, exist_ok=True)
    importance_df.to_csv(RESULTS_DIR / "random_forest_feature_importance.csv", index=False)

    top_display = importance_df.head(15).copy()
    top_display = top_display.iloc[::-1].reset_index(drop=True)

    fig, ax = plt.subplots(figsize=(8, 6))
    ax.barh(top_display["feature"], top_display["importance"], color="#4C78A8")
    ax.invert_yaxis()
    ax.set_title("Random Forest Feature Importance (Top 15)")
    ax.set_xlabel("Importance")
    ax.set_ylabel("Feature")
    fig.tight_layout()
    fig.savefig(RESULTS_DIR / "random_forest_feature_importance.png", dpi=200, bbox_inches="tight")
    plt.close(fig)

    return importance_df


def extract_logistic_coefficients(
    model_path: Path,
    feature_names: List[str],
) -> pd.DataFrame:
    """Extract class-specific logistic regression coefficients and save them as a CSV."""

    model = joblib.load(model_path)
    if "model" not in model.named_steps:
        raise ValueError("Loaded Logistic Regression artifact does not appear to be a sklearn pipeline.")

    classifier = model.named_steps["model"]
    coeff_matrix = np.asarray(classifier.coef_, dtype=float)
    classes = list(classifier.classes_)

    if coeff_matrix.shape[1] != len(feature_names):
        raise ValueError(
            f"Coefficient feature count mismatch for Logistic Regression: expected {len(feature_names)}, found {coeff_matrix.shape[1]}."
        )

    rows: List[Dict[str, Any]] = []
    for class_index, class_name in enumerate(classes):
        frame = pd.DataFrame(
            {
                "feature": feature_names,
                "class": class_name,
                "coefficient": coeff_matrix[class_index],
            }
        )
        frame["absolute_coefficient"] = frame["coefficient"].abs()
        frame = frame.sort_values("absolute_coefficient", ascending=False, kind="mergesort").reset_index(drop=True)
        frame["rank_within_class"] = np.arange(1, len(frame) + 1)
        rows.extend(frame[["feature", "class", "coefficient", "absolute_coefficient", "rank_within_class"]].to_dict("records"))

    coefficients_df = pd.DataFrame(rows)
    RESULTS_DIR.mkdir(parents=True, exist_ok=True)
    coefficients_df.to_csv(RESULTS_DIR / "logistic_regression_coefficients.csv", index=False)

    return coefficients_df


def infer_direction(feature: str) -> str:
    """Infer a conservative direction label for explanation metadata."""

    if feature in {
        "overwhelm_dimension",
        "stress_impact_dimension",
        "emotional_strain_dimension",
        "stress_persistence_dimension",
        "recovery_difficulty_dimension",
        "stress_behavior_dimension",
        "Q13_stress_aligned",
    }:
        return "increases_risk"

    if feature == "Q13_encoded":
        return "decreases_risk"

    if feature.startswith("Q10_") or feature.startswith("Q11_") or feature.startswith("Q2_") or feature.startswith("Q25_"):
        return "model_associated"

    return "model_associated"


def identify_top_features(
    selected_model: str,
    random_forest_importance: pd.DataFrame,
    logistic_coefficients: pd.DataFrame,
) -> List[Dict[str, Any]]:
    """Identify the top explanation features for the selected model."""

    if selected_model == "random_forest":
        top_df = random_forest_importance.head(5).copy()
        top_features = []
        for _, row in top_df.iterrows():
            top_features.append(
                {
                    "feature": row["feature"],
                    "importance": float(row["importance"]),
                    "direction": infer_direction(row["feature"]),
                }
            )
        return top_features

    top_df = logistic_coefficients.sort_values("absolute_coefficient", ascending=False, kind="mergesort").head(5).copy()
    top_features = []
    for _, row in top_df.iterrows():
        top_features.append(
            {
                "feature": row["feature"],
                "importance": float(row["absolute_coefficient"]),
                "direction": infer_direction(row["feature"]),
            }
        )
    return top_features


def calculate_confidence(probability_row: pd.Series) -> Dict[str, float | str]:
    """Calculate a transparent, bounded confidence score for one prediction."""

    probabilities = [float(probability_row[col]) for col in PROBABILITY_COLUMNS]
    sorted_probabilities = sorted(probabilities, reverse=True)
    max_probability = float(sorted_probabilities[0])
    second_probability = float(sorted_probabilities[1]) if len(sorted_probabilities) > 1 else 0.0
    probability_margin = max_probability - second_probability
    confidence = float(np.clip(0.5 * max_probability + 0.5 * probability_margin, 0.0, 1.0))

    if confidence >= CONFIDENCE_THRESHOLDS["high"]:
        confidence_level = "high"
    elif confidence >= CONFIDENCE_THRESHOLDS["moderate"]:
        confidence_level = "moderate"
    else:
        confidence_level = "low"

    return {
        "max_probability": max_probability,
        "second_probability": second_probability,
        "probability_margin": probability_margin,
        "confidence": confidence,
        "confidence_level": confidence_level,
    }


def analyze_oof_confidence(
    selected_model: str,
    model_comparison: pd.DataFrame,
) -> pd.DataFrame:
    """Analyze OOF confidence for the selected model."""

    selected_oof_path = RESULTS_DIR / f"oof_predictions_{selected_model}.csv"
    if not selected_oof_path.exists():
        raise FileNotFoundError(f"Selected model OOF predictions file not found: {selected_oof_path}")

    oof_df = pd.read_csv(selected_oof_path)

    if len(oof_df) != 52:
        raise ValueError(f"Expected exactly 52 OOF rows for {selected_model}, found {len(oof_df)}.")

    probability_matrix = oof_df[PROBABILITY_COLUMNS]
    if not ((probability_matrix >= 0).all().all() and (probability_matrix <= 1).all().all()):
        raise ValueError(f"Probability values must be between 0 and 1 in {selected_oof_path}.")

    if not np.allclose(probability_matrix.sum(axis=1), 1.0, atol=1e-6):
        raise ValueError(f"Probability rows do not sum to approximately 1 in {selected_oof_path}.")

    predicted_from_probabilities = probability_matrix.idxmax(axis=1).map(
        {"prob_low": "low", "prob_moderate": "moderate", "prob_high": "high"}
    )
    if not (oof_df["predicted_stress_level"] == predicted_from_probabilities).all():
        raise ValueError(f"OOF probability consistency check failed for {selected_model}.")

    confidence_records: List[Dict[str, Any]] = []
    for _, row in oof_df.iterrows():
        confidence_result = calculate_confidence(row)
        confidence_records.append(
            {
                "row_index": int(row["row_index"]),
                "true_stress_level": row["true_stress_level"],
                "predicted_stress_level": row["predicted_stress_level"],
                "prob_low": float(row["prob_low"]),
                "prob_moderate": float(row["prob_moderate"]),
                "prob_high": float(row["prob_high"]),
                "max_probability": confidence_result["max_probability"],
                "second_probability": confidence_result["second_probability"],
                "probability_margin": confidence_result["probability_margin"],
                "confidence": confidence_result["confidence"],
                "confidence_level": confidence_result["confidence_level"],
                "correct_prediction": bool(row["predicted_stress_level"] == row["true_stress_level"]),
            }
        )

    confidence_df = pd.DataFrame(confidence_records)
    confidence_df.to_csv(RESULTS_DIR / "oof_confidence_analysis.csv", index=False)

    return confidence_df


def generate_explainability_report(
    selected_model_record: Dict[str, Any],
    model_results: pd.DataFrame,
    random_forest_importance: pd.DataFrame,
    logistic_coefficients: pd.DataFrame,
    top_features: List[Dict[str, Any]],
    confidence_df: pd.DataFrame,
) -> str:
    """Generate the explainability report text file."""

    selected_model = selected_model_record["selected_model"]
    selected_row = model_results[model_results["model"] == selected_model].iloc[0]

    logistic_row = model_results[model_results["model"] == "logistic_regression"].iloc[0]
    random_forest_row = model_results[model_results["model"] == "random_forest"].iloc[0]

    top_random_forest = random_forest_importance.head(15).copy()
    summary_by_true_class = confidence_df.groupby("true_stress_level")["confidence"].mean().sort_index()

    correct_df = confidence_df[confidence_df["correct_prediction"] == True]
    incorrect_df = confidence_df[confidence_df["correct_prediction"] == False]

    lines: List[str] = [
        "Questionnaire Explainability Report",
        "==================================",
        "",
        f"Selected model: {selected_model}",
        f"Selection basis: {selected_model_record['selection_basis']}",
        "",
        "Model comparison (cross-validation based):",
        f"- Logistic Regression: Macro F1 mean={logistic_row['macro_f1_mean']:.4f}, Balanced Accuracy mean={logistic_row['balanced_accuracy_mean']:.4f}",
        f"- Random Forest: Macro F1 mean={random_forest_row['macro_f1_mean']:.4f}, Balanced Accuracy mean={random_forest_row['balanced_accuracy_mean']:.4f}",
        "",
        "Top Random Forest features (top 15):",
    ]

    for _, row in top_random_forest.iterrows():
        lines.append(
            f"- {int(row['rank'])}. {row['feature']}: importance={row['importance']:.6f}"
        )

    lines.extend(
        [
            "",
            "Logistic Regression coefficient summary:",
            "- Coefficients were extracted for each class and ranked within class by absolute coefficient magnitude.",
            "- Interpretation is model-association only; coefficients are not treated as causal effects.",
        ]
    )

    strongest_positive = logistic_coefficients.sort_values("coefficient", ascending=False).head(5)
    strongest_negative = logistic_coefficients.sort_values("coefficient", ascending=True).head(5)

    lines.append("- Strongest positive coefficients:")
    for _, row in strongest_positive.iterrows():
        lines.append(
            f"  * {row['class']}: {row['feature']} = {row['coefficient']:.6f}"
        )

    lines.append("- Strongest negative coefficients:")
    for _, row in strongest_negative.iterrows():
        lines.append(
            f"  * {row['class']}: {row['feature']} = {row['coefficient']:.6f}"
        )

    lines.extend(
        [
            "",
            "Confidence methodology:",
            "- Model confidence is a project-level heuristic, not clinical certainty.",
            "- For each OOF prediction, confidence is calculated as 0.5 * max_probability + 0.5 * probability_margin.",
            "- probability_margin = largest_probability - second_largest_probability.",
            "- confidence_level thresholds: high >= 0.70, moderate >= 0.50, else low.",
            "",
            "OOF confidence analysis:",
            f"- Mean confidence: {confidence_df['confidence'].mean():.4f}",
            f"- Median confidence: {confidence_df['confidence'].median():.4f}",
            f"- Standard deviation: {confidence_df['confidence'].std():.4f}",
            f"- Mean confidence by true class: low={summary_by_true_class.get('low', 0.0):.4f}, moderate={summary_by_true_class.get('moderate', 0.0):.4f}, high={summary_by_true_class.get('high', 0.0):.4f}",
            f"- Confidence for correct predictions: {correct_df['confidence'].mean():.4f}",
            f"- Confidence for incorrect predictions: {incorrect_df['confidence'].mean():.4f}",
            "",
            "Top factors for the selected model:",
        ]
    )

    for index, item in enumerate(top_features, start=1):
        lines.append(
            f"{index}. {item['feature']} (direction={item['direction']}, importance={item['importance']:.6f})"
        )

    lines.extend(
        [
            "",
            "Limitations:",
            "- Only 52 real respondents were available.",
            "- Explanations represent model associations, not causation.",
            "- Confidence is a project-level model-confidence indicator and is not clinical certainty.",
            "- The system is non-clinical.",
            "- Small sample size limits the reliability of explanations and confidence summaries.",
            "- Feature importance may be affected by correlated predictors.",
            "",
            "Validation notes:",
            "- Model selection was performed from cross-validation results only.",
            "- No retraining or hyperparameter tuning was performed in this step.",
        ]
    )

    report_path = RESULTS_DIR / "explainability_report.txt"
    report_path.write_text("\n".join(lines), encoding="utf-8")
    return report_path.read_text(encoding="utf-8")


def validate_explainability(
    selected_model_record: Dict[str, Any],
    feature_metadata: Dict[str, Any],
    random_forest_importance: pd.DataFrame,
    logistic_coefficients: pd.DataFrame,
    top_features: List[Dict[str, Any]],
    confidence_df: pd.DataFrame,
) -> None:
    """Validate explainability outputs and guard against leakage or malformed artifacts."""

    selected_model = selected_model_record["selected_model"]
    if selected_model not in {"logistic_regression", "random_forest"}:
        raise ValueError(f"Invalid selected model: {selected_model}")

    feature_names = feature_metadata.get("feature_names", [])
    if not feature_names:
        raise ValueError("Feature metadata does not contain approved feature names.")

    feature_count = len(feature_names)
    if feature_count != feature_metadata.get("feature_count", feature_count):
        raise ValueError("Feature metadata feature count does not match the stored feature list length.")

    if len(random_forest_importance) != feature_count:
        raise ValueError("Random Forest feature importance count does not match the number of predictor features.")

    if len(logistic_coefficients) != feature_count * len(CLASS_ORDER):
        raise ValueError("Logistic Regression coefficient record count does not match the feature count times the number of classes.")

    for item in top_features:
        if item["feature"] in TARGET_COLUMNS:
            raise ValueError(f"Top factors contain a target-related column: {item['feature']}")
        if item["feature"] in {"Q4", "Q4_encoded"}:
            raise ValueError(f"Top factors should not expose Q4/Q4_encoded: {item['feature']}")

    if not ((confidence_df["confidence"] >= 0).all() and (confidence_df["confidence"] <= 1).all()):
        raise ValueError("Confidence values must be between 0 and 1.")

    valid_levels = {"high", "moderate", "low"}
    if not confidence_df["confidence_level"].isin(valid_levels).all():
        raise ValueError("Confidence levels contain unexpected values.")

    if len(confidence_df) != 52:
        raise ValueError(f"OOF confidence analysis must contain exactly 52 rows, found {len(confidence_df)}.")

    if not np.allclose(confidence_df[["prob_low", "prob_moderate", "prob_high"]].sum(axis=1), 1.0, atol=1e-6):
        raise ValueError("OOF confidence analysis probabilities do not sum to approximately 1.")

    predicted_from_probabilities = confidence_df[["prob_low", "prob_moderate", "prob_high"]].idxmax(axis=1).map(
        {"prob_low": "low", "prob_moderate": "moderate", "prob_high": "high"}
    )
    if not (confidence_df["predicted_stress_level"] == predicted_from_probabilities).all():
        raise ValueError("OOF confidence analysis failed probability/prediction consistency validation.")

    selected_model_file = MODELS_DIR / f"{selected_model}.joblib"
    if not selected_model_file.exists():
        raise FileNotFoundError(f"Selected model artifact not found: {selected_model_file}")


def run_explainability() -> Dict[str, Any]:
    """Run the full explainability workflow."""

    model_results = load_model_results()
    feature_metadata = load_feature_metadata()
    training_metadata = load_training_metadata()

    selected_model_record = select_model(model_results)
    selected_model = selected_model_record["selected_model"]

    feature_names = feature_metadata.get("feature_names", [])
    if len(feature_names) != feature_metadata.get("feature_count", len(feature_names)):
        raise ValueError("Feature metadata is inconsistent.")

    random_forest_importance = extract_random_forest_importance(MODELS_DIR / "random_forest.joblib", feature_names)
    logistic_coefficients = extract_logistic_coefficients(MODELS_DIR / "logistic_regression.joblib", feature_names)

    top_features = identify_top_features(selected_model, random_forest_importance, logistic_coefficients)

    confidence_df = analyze_oof_confidence(selected_model, model_results)

    confidence_method = (
        "confidence = 0.5 * max_probability + 0.5 * probability_margin, "
        "where probability_margin = largest_probability - second_largest_probability."
    )

    save_explainability_metadata(
        selected_model=selected_model,
        top_features=top_features,
        confidence_method=confidence_method,
        confidence_thresholds=CONFIDENCE_THRESHOLDS,
    )

    generate_explainability_report(
        selected_model_record=selected_model_record,
        model_results=model_results,
        random_forest_importance=random_forest_importance,
        logistic_coefficients=logistic_coefficients,
        top_features=top_features,
        confidence_df=confidence_df,
    )

    validate_explainability(
        selected_model_record=selected_model_record,
        feature_metadata=feature_metadata,
        random_forest_importance=random_forest_importance,
        logistic_coefficients=logistic_coefficients,
        top_features=top_features,
        confidence_df=confidence_df,
    )

    return {
        "selected_model": selected_model,
        "selected_model_record": selected_model_record,
        "random_forest_importance": random_forest_importance,
        "logistic_coefficients": logistic_coefficients,
        "top_features": top_features,
        "confidence_df": confidence_df,
        "training_metadata": training_metadata,
        "feature_metadata": feature_metadata,
    }


def main() -> None:
    """Run the explainability workflow and print a concise summary."""

    results = run_explainability()

    selected_model = results["selected_model"]
    confidence_df = results["confidence_df"]
    top_features = results["top_features"]

    model_results = load_model_results()
    logistic_row = model_results[model_results["model"] == "logistic_regression"].iloc[0]
    random_forest_row = model_results[model_results["model"] == "random_forest"].iloc[0]

    print("QUESTIONNAIRE EXPLAINABILITY COMPLETE")
    print(f"Selected model: {selected_model}")
    print()
    print("Model comparison:")
    print(
        f"Logistic Regression Macro F1: {logistic_row['macro_f1_mean']:.4f}"
    )
    print(
        f"Random Forest Macro F1: {random_forest_row['macro_f1_mean']:.4f}"
    )
    print()
    print("Top features:")
    for index, item in enumerate(top_features[:5], start=1):
        print(f"{index}. {item['feature']}")
    print()
    print("Confidence analysis:")
    print(f"Mean confidence: {confidence_df['confidence'].mean():.4f}")
    print(f"Median confidence: {confidence_df['confidence'].median():.4f}")
    print()
    print("Validation:")
    print("Model selection: PASS")
    print("Feature mapping: PASS")
    print("OOF probability consistency: PASS")
    print("Confidence validation: PASS")
    print()
    print("Outputs:")
    print("results/questionnaire/explainability_report.txt")
    print("results/questionnaire/random_forest_feature_importance.csv")
    print("results/questionnaire/random_forest_feature_importance.png")
    print("results/questionnaire/logistic_regression_coefficients.csv")
    print("results/questionnaire/oof_confidence_analysis.csv")
    print("models/questionnaire/selected_model.json")
    print("models/questionnaire/explainability_metadata.json")


if __name__ == "__main__":
    main()
